coercion_strategy: Coercion/ISO8601->DateTime
created_at: '2026-09-28T19:13:37.170231Z'
effective_type: type/DateTime
serdes/meta:
- id: Trivia DB
  model: Database
- id: quiz
  model: Table
- id: createdAt
  model: Field
- id: '1'
  model: FieldUserSettings
